export type Move = {
  name: string;
  power: number;
  pp: number;
  maxPp: number;
  damageClass?: string;
  type?: string;
  accuracy?: number | null;
  statChanges?: { stat: string; change: number }[];
  description?: string | null;
  priority?: number | null;
};
export type Pokemon = {
  id?: number | string;
  pk_order?: number;
  name: string;
  level: number;
  type: string[];
  hp: number;
  maxHp: number;
  attack: number;
  defense: number;
  specialAttack: number;
  specialDefense: number;
  speed: number;
  frontImage: string;
  backImage: string;
  isShiny?: boolean;
  moves: Move[];
  cry: string;
};
