/**
 * evolutions.ts — static Gen 1 + Gen 2 Pokémon evolution data
 *
 * Auto-generated by scrape-evolutions.mjs — do not edit by hand.
 * Re-run the script if evolution data needs updating.
 *
 * Each entry describes one evolution step: a (from → to) pair with
 * a typed condition explaining what triggers the evolution.
 *
 * ──────────────────────────────────────────────────────────────────
 * DATA STRUCTURE DESIGN NOTES
 * ──────────────────────────────────────────────────────────────────
 *
 * EvolutionCondition is a discriminated union on the `trigger` field.
 * This lets TypeScript narrow the type safely and lets your app filter
 * to only the triggers it supports:
 *
 *   const levelUps = EVOLUTIONS.filter(
 *     (e): e is EvolutionStep<LevelUpCondition> =>
 *       e.condition.trigger === "level-up"
 *   );
 *
 * Current trigger types in Gen 1+2:
 *
 *   "level-up"   — Pokémon reaches a specific level.
 *                  condition.level holds the required level.
 *                  This is your current app scope.
 *
 *   "trade"      — Pokémon is traded.
 *                  condition.heldItem is non-null when a held item is
 *                  required (e.g. Onix + Metal Coat → Steelix).
 *
 *   "use-item"   — A specific item is used on the Pokémon.
 *                  condition.item names the stone / item.
 *                  (e.g. "water-stone", "fire-stone", "moon-stone")
 *
 *   "happiness"  — Pokémon has high friendship (≥220).
 *                  condition.timeOfDay is "day", "night", or null.
 *                  (e.g. Eevee → Espeon is "day", → Umbreon is "night")
 *
 *   "other"      — Edge cases (Tyrogue stat check, etc.)
 *                  condition.note is a human-readable description.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type LevelUpCondition = {
  trigger: "level-up";
  /** Minimum level required to evolve. */
  level: number;
};

export type TradeCondition = {
  trigger: "trade";
  /** Item that must be held during trade, or null if no item needed. */
  heldItem: string | null;
};

export type UseItemCondition = {
  trigger: "use-item";
  /** Name of the evolution item (e.g. "water-stone", "moon-stone"). */
  item: string;
};

export type HappinessCondition = {
  trigger: "happiness";
  /** Time of day restriction, or null if any time works. */
  timeOfDay: "day" | "night" | null;
};

export type OtherCondition = {
  trigger: "other";
  /** Human-readable description of the special requirement. */
  note: string;
};

/** Discriminated union — narrow via `condition.trigger`. */
export type EvolutionCondition =
  | LevelUpCondition
  | TradeCondition
  | UseItemCondition
  | HappinessCondition
  | OtherCondition;

export type EvolutionStep<C extends EvolutionCondition = EvolutionCondition> = {
  /** National Pokédex ID of the pre-evolution. */
  fromId: number;
  fromName: string;
  /** National Pokédex ID of the evolved form. */
  toId: number;
  toName: string;
  /** Typed condition describing what triggers this evolution. */
  condition: C;
};

// ─── Data ─────────────────────────────────────────────────────────────────────

export const EVOLUTIONS: EvolutionStep[] = [
  {
    fromId: 1,
    fromName: "bulbasaur",
    toId: 2,
    toName: "ivysaur",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 2,
    fromName: "ivysaur",
    toId: 3,
    toName: "venusaur",
    condition: { trigger: "level-up", level: 32 },
  },
  {
    fromId: 4,
    fromName: "charmander",
    toId: 5,
    toName: "charmeleon",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 5,
    fromName: "charmeleon",
    toId: 6,
    toName: "charizard",
    condition: { trigger: "level-up", level: 36 },
  },
  {
    fromId: 7,
    fromName: "squirtle",
    toId: 8,
    toName: "wartortle",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 8,
    fromName: "wartortle",
    toId: 9,
    toName: "blastoise",
    condition: { trigger: "level-up", level: 36 },
  },
  {
    fromId: 10,
    fromName: "caterpie",
    toId: 11,
    toName: "metapod",
    condition: { trigger: "level-up", level: 7 },
  },
  {
    fromId: 11,
    fromName: "metapod",
    toId: 12,
    toName: "butterfree",
    condition: { trigger: "level-up", level: 10 },
  },
  {
    fromId: 13,
    fromName: "weedle",
    toId: 14,
    toName: "kakuna",
    condition: { trigger: "level-up", level: 7 },
  },
  {
    fromId: 14,
    fromName: "kakuna",
    toId: 15,
    toName: "beedrill",
    condition: { trigger: "level-up", level: 10 },
  },
  {
    fromId: 16,
    fromName: "pidgey",
    toId: 17,
    toName: "pidgeotto",
    condition: { trigger: "level-up", level: 18 },
  },
  {
    fromId: 17,
    fromName: "pidgeotto",
    toId: 18,
    toName: "pidgeot",
    condition: { trigger: "level-up", level: 36 },
  },
  {
    fromId: 19,
    fromName: "rattata",
    toId: 20,
    toName: "raticate",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 21,
    fromName: "spearow",
    toId: 22,
    toName: "fearow",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 23,
    fromName: "ekans",
    toId: 24,
    toName: "arbok",
    condition: { trigger: "level-up", level: 22 },
  },
  {
    fromId: 25,
    fromName: "pikachu",
    toId: 26,
    toName: "raichu",
    condition: { trigger: "use-item", item: "thunder-stone" },
  },
  {
    fromId: 27,
    fromName: "sandshrew",
    toId: 28,
    toName: "sandslash",
    condition: { trigger: "level-up", level: 22 },
  },
  {
    fromId: 29,
    fromName: "nidoran-f",
    toId: 30,
    toName: "nidorina",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 30,
    fromName: "nidorina",
    toId: 31,
    toName: "nidoqueen",
    condition: { trigger: "use-item", item: "moon-stone" },
  },
  {
    fromId: 32,
    fromName: "nidoran-m",
    toId: 33,
    toName: "nidorino",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 33,
    fromName: "nidorino",
    toId: 34,
    toName: "nidoking",
    condition: { trigger: "use-item", item: "moon-stone" },
  },
  {
    fromId: 35,
    fromName: "clefairy",
    toId: 36,
    toName: "clefable",
    condition: { trigger: "use-item", item: "moon-stone" },
  },
  {
    fromId: 37,
    fromName: "vulpix",
    toId: 38,
    toName: "ninetales",
    condition: { trigger: "use-item", item: "fire-stone" },
  },
  {
    fromId: 39,
    fromName: "jigglypuff",
    toId: 40,
    toName: "wigglytuff",
    condition: { trigger: "use-item", item: "moon-stone" },
  },
  {
    fromId: 41,
    fromName: "zubat",
    toId: 42,
    toName: "golbat",
    condition: { trigger: "level-up", level: 22 },
  },
  {
    fromId: 42,
    fromName: "golbat",
    toId: 169,
    toName: "crobat",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 43,
    fromName: "oddish",
    toId: 44,
    toName: "gloom",
    condition: { trigger: "level-up", level: 21 },
  },
  {
    fromId: 44,
    fromName: "gloom",
    toId: 45,
    toName: "vileplume",
    condition: { trigger: "use-item", item: "leaf-stone" },
  },
  {
    fromId: 44,
    fromName: "gloom",
    toId: 182,
    toName: "bellossom",
    condition: { trigger: "use-item", item: "sun-stone" },
  },
  {
    fromId: 46,
    fromName: "paras",
    toId: 47,
    toName: "parasect",
    condition: { trigger: "level-up", level: 24 },
  },
  {
    fromId: 48,
    fromName: "venonat",
    toId: 49,
    toName: "venomoth",
    condition: { trigger: "level-up", level: 31 },
  },
  {
    fromId: 50,
    fromName: "diglett",
    toId: 51,
    toName: "dugtrio",
    condition: { trigger: "level-up", level: 26 },
  },
  {
    fromId: 52,
    fromName: "meowth",
    toId: 53,
    toName: "persian",
    condition: { trigger: "level-up", level: 28 },
  },
  {
    fromId: 54,
    fromName: "psyduck",
    toId: 55,
    toName: "golduck",
    condition: { trigger: "level-up", level: 33 },
  },
  {
    fromId: 56,
    fromName: "mankey",
    toId: 57,
    toName: "primeape",
    condition: { trigger: "level-up", level: 28 },
  },
  {
    fromId: 58,
    fromName: "growlithe",
    toId: 59,
    toName: "arcanine",
    condition: { trigger: "use-item", item: "fire-stone" },
  },
  {
    fromId: 60,
    fromName: "poliwag",
    toId: 61,
    toName: "poliwhirl",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 61,
    fromName: "poliwhirl",
    toId: 62,
    toName: "poliwrath",
    condition: { trigger: "use-item", item: "water-stone" },
  },
  {
    fromId: 61,
    fromName: "poliwhirl",
    toId: 186,
    toName: "politoed",
    condition: { trigger: "trade", heldItem: "kings-rock" },
  },
  {
    fromId: 63,
    fromName: "abra",
    toId: 64,
    toName: "kadabra",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 64,
    fromName: "kadabra",
    toId: 65,
    toName: "alakazam",
    condition: { trigger: "trade", heldItem: null },
  },
  {
    fromId: 66,
    fromName: "machop",
    toId: 67,
    toName: "machoke",
    condition: { trigger: "level-up", level: 28 },
  },
  {
    fromId: 67,
    fromName: "machoke",
    toId: 68,
    toName: "machamp",
    condition: { trigger: "trade", heldItem: null },
  },
  {
    fromId: 69,
    fromName: "bellsprout",
    toId: 70,
    toName: "weepinbell",
    condition: { trigger: "level-up", level: 21 },
  },
  {
    fromId: 70,
    fromName: "weepinbell",
    toId: 71,
    toName: "victreebel",
    condition: { trigger: "use-item", item: "leaf-stone" },
  },
  {
    fromId: 72,
    fromName: "tentacool",
    toId: 73,
    toName: "tentacruel",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 74,
    fromName: "geodude",
    toId: 75,
    toName: "graveler",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 75,
    fromName: "graveler",
    toId: 76,
    toName: "golem",
    condition: { trigger: "trade", heldItem: null },
  },
  {
    fromId: 77,
    fromName: "ponyta",
    toId: 78,
    toName: "rapidash",
    condition: { trigger: "level-up", level: 40 },
  },
  {
    fromId: 79,
    fromName: "slowpoke",
    toId: 80,
    toName: "slowbro",
    condition: { trigger: "level-up", level: 37 },
  },
  {
    fromId: 79,
    fromName: "slowpoke",
    toId: 199,
    toName: "slowking",
    condition: { trigger: "trade", heldItem: "kings-rock" },
  },
  {
    fromId: 81,
    fromName: "magnemite",
    toId: 82,
    toName: "magneton",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 84,
    fromName: "doduo",
    toId: 85,
    toName: "dodrio",
    condition: { trigger: "level-up", level: 31 },
  },
  {
    fromId: 86,
    fromName: "seel",
    toId: 87,
    toName: "dewgong",
    condition: { trigger: "level-up", level: 34 },
  },
  {
    fromId: 88,
    fromName: "grimer",
    toId: 89,
    toName: "muk",
    condition: { trigger: "level-up", level: 38 },
  },
  {
    fromId: 90,
    fromName: "shellder",
    toId: 91,
    toName: "cloyster",
    condition: { trigger: "use-item", item: "water-stone" },
  },
  {
    fromId: 92,
    fromName: "gastly",
    toId: 93,
    toName: "haunter",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 93,
    fromName: "haunter",
    toId: 94,
    toName: "gengar",
    condition: { trigger: "level-up", level: 36 },
  },
  {
    fromId: 95,
    fromName: "onix",
    toId: 208,
    toName: "steelix",
    condition: { trigger: "trade", heldItem: "metal-coat" },
  },
  {
    fromId: 96,
    fromName: "drowzee",
    toId: 97,
    toName: "hypno",
    condition: { trigger: "level-up", level: 26 },
  },
  {
    fromId: 98,
    fromName: "krabby",
    toId: 99,
    toName: "kingler",
    condition: { trigger: "level-up", level: 28 },
  },
  {
    fromId: 100,
    fromName: "voltorb",
    toId: 101,
    toName: "electrode",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 102,
    fromName: "exeggcute",
    toId: 103,
    toName: "exeggutor",
    condition: { trigger: "use-item", item: "leaf-stone" },
  },
  {
    fromId: 104,
    fromName: "cubone",
    toId: 105,
    toName: "marowak",
    condition: { trigger: "level-up", level: 28 },
  },
  {
    fromId: 109,
    fromName: "koffing",
    toId: 110,
    toName: "weezing",
    condition: { trigger: "level-up", level: 35 },
  },
  {
    fromId: 111,
    fromName: "rhyhorn",
    toId: 112,
    toName: "rhydon",
    condition: { trigger: "level-up", level: 42 },
  },
  {
    fromId: 113,
    fromName: "chansey",
    toId: 242,
    toName: "blissey",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 116,
    fromName: "horsea",
    toId: 117,
    toName: "seadra",
    condition: { trigger: "level-up", level: 32 },
  },
  {
    fromId: 117,
    fromName: "seadra",
    toId: 230,
    toName: "kingdra",
    condition: { trigger: "trade", heldItem: "dragon-scale" },
  },
  {
    fromId: 118,
    fromName: "goldeen",
    toId: 119,
    toName: "seaking",
    condition: { trigger: "level-up", level: 33 },
  },
  {
    fromId: 120,
    fromName: "staryu",
    toId: 121,
    toName: "starmie",
    condition: { trigger: "use-item", item: "water-stone" },
  },
  {
    fromId: 123,
    fromName: "scyther",
    toId: 212,
    toName: "scizor",
    condition: { trigger: "trade", heldItem: "metal-coat" },
  },
  {
    fromId: 129,
    fromName: "magikarp",
    toId: 130,
    toName: "gyarados",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 133,
    fromName: "eevee",
    toId: 134,
    toName: "vaporeon",
    condition: { trigger: "use-item", item: "water-stone" },
  },
  {
    fromId: 133,
    fromName: "eevee",
    toId: 135,
    toName: "jolteon",
    condition: { trigger: "use-item", item: "thunder-stone" },
  },
  {
    fromId: 133,
    fromName: "eevee",
    toId: 136,
    toName: "flareon",
    condition: { trigger: "use-item", item: "fire-stone" },
  },
  {
    fromId: 133,
    fromName: "eevee",
    toId: 196,
    toName: "espeon",
    condition: { trigger: "happiness", timeOfDay: "day" },
  },
  {
    fromId: 133,
    fromName: "eevee",
    toId: 197,
    toName: "umbreon",
    condition: { trigger: "happiness", timeOfDay: "night" },
  },
  {
    fromId: 137,
    fromName: "porygon",
    toId: 233,
    toName: "porygon2",
    condition: { trigger: "trade", heldItem: "up-grade" },
  },
  {
    fromId: 138,
    fromName: "omanyte",
    toId: 139,
    toName: "omastar",
    condition: { trigger: "level-up", level: 40 },
  },
  {
    fromId: 140,
    fromName: "kabuto",
    toId: 141,
    toName: "kabutops",
    condition: { trigger: "level-up", level: 40 },
  },
  {
    fromId: 147,
    fromName: "dratini",
    toId: 148,
    toName: "dragonair",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 148,
    fromName: "dragonair",
    toId: 149,
    toName: "dragonite",
    condition: { trigger: "level-up", level: 55 },
  },
  {
    fromId: 152,
    fromName: "chikorita",
    toId: 153,
    toName: "bayleef",
    condition: { trigger: "level-up", level: 16 },
  },
  {
    fromId: 153,
    fromName: "bayleef",
    toId: 154,
    toName: "meganium",
    condition: { trigger: "level-up", level: 32 },
  },
  {
    fromId: 155,
    fromName: "cyndaquil",
    toId: 156,
    toName: "quilava",
    condition: { trigger: "level-up", level: 14 },
  },
  {
    fromId: 156,
    fromName: "quilava",
    toId: 157,
    toName: "typhlosion",
    condition: { trigger: "level-up", level: 36 },
  },
  {
    fromId: 158,
    fromName: "totodile",
    toId: 159,
    toName: "croconaw",
    condition: { trigger: "level-up", level: 18 },
  },
  {
    fromId: 159,
    fromName: "croconaw",
    toId: 160,
    toName: "feraligatr",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 161,
    fromName: "sentret",
    toId: 162,
    toName: "furret",
    condition: { trigger: "level-up", level: 15 },
  },
  {
    fromId: 163,
    fromName: "hoothoot",
    toId: 164,
    toName: "noctowl",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 165,
    fromName: "ledyba",
    toId: 166,
    toName: "ledian",
    condition: { trigger: "level-up", level: 18 },
  },
  {
    fromId: 167,
    fromName: "spinarak",
    toId: 168,
    toName: "ariados",
    condition: { trigger: "level-up", level: 22 },
  },
  {
    fromId: 170,
    fromName: "chinchou",
    toId: 171,
    toName: "lanturn",
    condition: { trigger: "level-up", level: 27 },
  },
  {
    fromId: 172,
    fromName: "pichu",
    toId: 25,
    toName: "pikachu",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 173,
    fromName: "cleffa",
    toId: 35,
    toName: "clefairy",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 174,
    fromName: "igglybuff",
    toId: 39,
    toName: "jigglypuff",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 175,
    fromName: "togepi",
    toId: 176,
    toName: "togetic",
    condition: { trigger: "happiness", timeOfDay: null },
  },
  {
    fromId: 177,
    fromName: "natu",
    toId: 178,
    toName: "xatu",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 179,
    fromName: "mareep",
    toId: 180,
    toName: "flaaffy",
    condition: { trigger: "level-up", level: 15 },
  },
  {
    fromId: 180,
    fromName: "flaaffy",
    toId: 181,
    toName: "ampharos",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 183,
    fromName: "marill",
    toId: 184,
    toName: "azumarill",
    condition: { trigger: "level-up", level: 18 },
  },
  {
    fromId: 187,
    fromName: "hoppip",
    toId: 188,
    toName: "skiploom",
    condition: { trigger: "level-up", level: 18 },
  },
  {
    fromId: 188,
    fromName: "skiploom",
    toId: 189,
    toName: "jumpluff",
    condition: { trigger: "level-up", level: 27 },
  },
  {
    fromId: 191,
    fromName: "sunkern",
    toId: 192,
    toName: "sunflora",
    condition: { trigger: "use-item", item: "sun-stone" },
  },
  {
    fromId: 194,
    fromName: "wooper",
    toId: 195,
    toName: "quagsire",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 204,
    fromName: "pineco",
    toId: 205,
    toName: "forretress",
    condition: { trigger: "level-up", level: 31 },
  },
  {
    fromId: 209,
    fromName: "snubbull",
    toId: 210,
    toName: "granbull",
    condition: { trigger: "level-up", level: 23 },
  },
  {
    fromId: 216,
    fromName: "teddiursa",
    toId: 217,
    toName: "ursaring",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 218,
    fromName: "slugma",
    toId: 219,
    toName: "magcargo",
    condition: { trigger: "level-up", level: 38 },
  },
  {
    fromId: 220,
    fromName: "swinub",
    toId: 221,
    toName: "piloswine",
    condition: { trigger: "level-up", level: 33 },
  },
  {
    fromId: 223,
    fromName: "remoraid",
    toId: 224,
    toName: "octillery",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 228,
    fromName: "houndour",
    toId: 229,
    toName: "houndoom",
    condition: { trigger: "level-up", level: 24 },
  },
  {
    fromId: 231,
    fromName: "phanpy",
    toId: 232,
    toName: "donphan",
    condition: { trigger: "level-up", level: 25 },
  },
  {
    fromId: 236,
    fromName: "tyrogue",
    toId: 106,
    toName: "hitmonlee",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 236,
    fromName: "tyrogue",
    toId: 107,
    toName: "hitmonchan",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 236,
    fromName: "tyrogue",
    toId: 237,
    toName: "hitmontop",
    condition: { trigger: "level-up", level: 20 },
  },
  {
    fromId: 238,
    fromName: "smoochum",
    toId: 124,
    toName: "jynx",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 239,
    fromName: "elekid",
    toId: 125,
    toName: "electabuzz",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 240,
    fromName: "magby",
    toId: 126,
    toName: "magmar",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 246,
    fromName: "larvitar",
    toId: 247,
    toName: "pupitar",
    condition: { trigger: "level-up", level: 30 },
  },
  {
    fromId: 247,
    fromName: "pupitar",
    toId: 248,
    toName: "tyranitar",
    condition: { trigger: "level-up", level: 55 },
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns the evolution step for a given Pokémon ID, if one exists.
 * Useful for your current level-up scope:
 *
 *   const step = getEvolution(pokemonId);
 *   if (step?.condition.trigger === "level-up" && currentLevel >= step.condition.level) {
 *     evolve(pokemon, step.toId);
 *   }
 */
export function getEvolution(fromId: number): EvolutionStep | undefined {
  return EVOLUTIONS.find((e) => e.fromId === fromId);
}

/**
 * Returns ALL evolution steps for a Pokémon ID.
 * Needed for branching evolutions like Eevee (8 possible evolutions).
 */
export function getAllEvolutions(fromId: number): EvolutionStep[] {
  return EVOLUTIONS.filter((e) => e.fromId === fromId);
}

/**
 * Returns only level-up evolutions — your current app scope.
 * TypeScript will narrow condition to LevelUpCondition automatically.
 */
export function getLevelUpEvolutions(): EvolutionStep<LevelUpCondition>[] {
  return EVOLUTIONS.filter(
    (e): e is EvolutionStep<LevelUpCondition> =>
      e.condition.trigger === "level-up",
  );
}
